reset;
reset;

option solver cplexamp;

model declaration_rummikub.ampl.mod;
data instance_rummikub.ampl.dat;
model build_groups.ampl.dat;
model model.mod;

printf "\nCONFIGURATION INITIALE \n";
printf"\nCarte_table: \n";
for{m in 1..NB_NUM} {
	for{n in 1..NB_COUL} {
		printf"%d ", carte_table[m,n];
	}
	printf"\n";
}
printf"\nCarte_main: \n";
for{m in 1..NB_NUM} {
	for{n in 1..NB_COUL} {
		printf"%d ", carte_main[m,n];
	}
	printf"\n";
}

solve;
